apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: environments.salaboy.com
spec:
  group: salaboy.com
  names:
    kind: Environment
    plural: environments
    shortNames:
      - "env"
      - "envs"
  versions:
  - additionalPrinterColumns:
    - jsonPath: .spec.parameters.size
      name: SIZE
      type: string
    name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties: 
              parameters: 
                type: object
                properties:
                  size:
                    type: string   
                required:   
            required: 
            - parameters          

     
            