apiVersion: v1
kind: ServiceAccount
metadata:
  name: api-server-source-sa

--- 

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: api-server-source-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - get
  - list
  - watch

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: api-server-source-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: api-server-source-role
subjects:
- kind: ServiceAccount
  name: api-server-source-sa
  namespace: default

---

apiVersion: sources.knative.dev/v1
kind: ApiServerSource
metadata:
 name: main-api-server-source
spec:
 serviceAccountName: api-server-source-sa
 mode: Resource
 resources:
   - apiVersion: v1
     kind: Event
 sink:
   ref:
     apiVersion: serving.knative.dev/v1
     kind: Service
     name: cloudevents-raw-endpoint
     namespace: four-keys


---

apiVersion: sources.knative.dev/v1
kind: ApiServerSource
metadata:
 name: sockeye-api-server-source
spec:
 serviceAccountName: api-server-source-sa
 mode: Resource
 resources:
   - apiVersion: v1
     kind: Event
 sink:
   ref:
     apiVersion: serving.knative.dev/v1
     kind: Service
     name: sockeye
     namespace: default     