apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: staging-environment-pipeline
  namespace: default
  annotations:
    description: |
      Sync Staging Environment
spec:
  params:
    - name: gitRepository
      description: The git repository that hosts context and Dockerfile
      default: https://github.com/salaboy/fmtok8s-staging-env
    - name: gitRevision
      description: The git revision to build
      default: main
  results:
  workspaces:
    - name: sources
      description: Workspace where the git repo is prepared for building  
  tasks:
    - name: clone-repo
      taskRef:
        name: git-clone
        bundle: gcr.io/tekton-releases/catalog/upstream/git-clone:0.4
      params:
        - name: url
          value: $(params.gitRepository)
        - name: revision
          value: $(params.gitRevision)
      workspaces:
        - name: output
          workspace: sources
    - name: helmfile-template
      runAfter: [clone-repo]
      workspaces:
        - name: sources
          workspace: sources
      taskSpec:
        workspaces:
          - name: sources
        steps:
          - name: deploy
            image: quay.io/roboll/helmfile:helm3-v0.135.0
            script: |
              #!/bin/sh
              set -ex

              cd $(workspaces.sources.path)

              helmfile repos

              helmfile template > final.yaml

              helmfile sync
        

              
              
